services:
  patchright:
    image: ghcr.io/voiddeficit/patchright-vnc:latest
    container_name: patchright
    restart: unless-stopped
    ports:
      - "5901:5900" # VNC
    environment:
      - NODE_PATH=/opt/deps/node_modules
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./app/:/opt/app
    working_dir: /opt/app